#应用级配置
APP_NAME: "tmaic"
APP_KEY: "p310544c037bb1026E4rnLJmpPmJ5f5SP46WXDk3ff17a71407b91747c2jHeeBe7"
APP_ENV: "local"
APP_LOCALE: "zh"
APP_URL: "http://192.168.0.199:6000"
LOGFILE: "./commonApp/storage/logs/sql.log"

AUTH_SIGN_KEY: "8rWZika5Ekes9Eel65ksf6E4rnLJmpPmJ5f5SP46W"
TOKE_KEY_ENCRYPTION: "true"

CACHE_DRIVER: "redis"
REDIS_HOST: "192.168.0.199"
REDIS_PORT: "6379"
REDIS_PASSWORD: ""
REDIS_DB: "0"
REDIS_CACHE_DB: "1"
TOKEN_TIME : 600
CACHE_TIME : 1

QUEUE_CONNECTION: "nsq"


QUEUE_NSQD_TCP_HOST: "127.0.0.1"
QUEUE_NSQD_TCP_PORT: "4150"
QUEUE_NSQLOOKUPD_HTTP_HOST: "http://127.0.0.1"
QUEUE_NSQLOOKUPD_HTTP_PORT: "4161"
QUEUE_MAX_IN_FLIGHT:  "50"
STORAGE: "./commonApp/storage"

